#!/bin/bash
- name: demo on filters
  hosts: local
  connection: local
  vars:
    topics: Linux , Shell , Ansible , Terraform # String
    tagsMap:
      name: ansible
      project: roboshop
      component: catalogue
    tagsList: [
        {
            "key": "name",
            "value": "ansible"
        },
        {
            "key": "project",
            "value": "roboshop"
        },
        {
            "key": "component",
            "value": "catalogue"
        }
    ]

  tasks:
  - name: greeting
    ansible.builtin.debug:
      msg: "Hi Phani , {{GREETING | default('Good Morning')}}"

  - name: convert string to list
    ansible.builtin.debug:
      msg: "{{ topics | split (',')}}"

  - name: conver map to list
    ansible.builtin.debug:
      msg: "{{ tagsMap | dict2items }}"

  - name: convert list to map
    ansible.builtin.debug:
      msg: "{{ tagsList | items2dict }}"

  - name: read students yaml 
    ansible.builtin.set_fact: # setting the variable dynamically
      student_yaml: "{{ lookup ('file', 'students.yaml' ) | from_yaml }}"

  - name: convert yaml to json
    ansible.builtin.debug:
      msg: "{{ student_yaml | to_nice_json }}"




