#!/bin/bash
- name: demo on loops
  hosts: local
  connection: local
  tasks:
  - name: print names
    ansible.builtin.debug:
      msg: "Hello {{ item }}" # item is reserved keyword in ansible.
    loop:
    - Phani
    - Kesava
    - Dasu   